export const SEARCH_TRIGGER_SEARCH = 'SEARCH_TRIGGER_SEARCH';

export const EXECUTE_SEARCH_FETCH_REQUEST = 'EXECUTE_SEARCH_FETCH_REQUEST';
export const EXECUTE_SEARCH_FETCH_SUCCESS = 'EXECUTE_SEARCH_FETCH_SUCCESS';
export const EXECUTE_SEARCH_FETCH_ERROR = 'EXECUTE_SEARCH_FETCH_ERROR';
